# Generated by Django 5.0.3 on 2025-10-10 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetiteur_ia', '0001_initial'),
        ('utilisateurs', '0002_alter_utilisateur_push_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('dernier_acces', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_ia', to='utilisateurs.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='MessageIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('élève', 'Élève'), ('ia', 'IA')], max_length=10)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='repetiteur_ia.sessionia')),
            ],
        ),
    ]
