# Generated by Django 5.0.3 on 2025-10-24 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_merge_0002_emploidutemps_document_0004_cours_fichier'),
        ('repetiteur_ia', '0003_alter_notification_options_embeddingia'),
        ('utilisateurs', '0004_delete_emailconfirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('cours', 'Cours'), ('exercice', 'Exercice'), ('corrige', 'Corrigé'), ('resume', 'Résumé'), ('video', 'Vidéo'), ('audio', 'Audio')], max_length=20)),
                ('matiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents_pedagogiques/%Y/%m/%d/')),
                ('contenu_texte', models.TextField(blank=True)),
                ('auteur', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_public', models.BooleanField(default=False)),
                ('mots_cles', models.TextField(blank=True, help_text='Mots-clés séparés par des virgules')),
            ],
            options={
                'verbose_name': 'Document pédagogique',
                'verbose_name_plural': 'Documents pédagogiques',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('rappel', 'Rappel'), ('paiement', 'Paiement'), ('nouveau_cours', 'Nouveau cours'), ('quiz', 'Quiz'), ('session_revision', 'Session de révision')], max_length=20),
        ),
        migrations.CreateModel(
            name='SessionRevisionProgrammee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_programmation', models.DateTimeField()),
                ('duree_prevue', models.IntegerField(default=45)),
                ('statut', models.CharField(choices=[('programmee', 'Programmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='programmee', max_length=20)),
                ('objectifs', models.TextField(blank=True)),
                ('notes_preparation', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_revision', to='utilisateurs.eleve')),
                ('emploi_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_revision', to='cours.emploidutemps')),
            ],
            options={
                'verbose_name': 'Session de révision programmée',
                'verbose_name_plural': 'Sessions de révision programmées',
                'ordering': ['date_programmation'],
            },
        ),
        migrations.CreateModel(
            name='RappelRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_rappel', models.DateTimeField()),
                ('envoye', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels_revision', to='utilisateurs.eleve')),
                ('session_programmee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repetiteur_ia.sessionrevisionprogrammee')),
            ],
            options={
                'verbose_name': 'Rappel de révision',
                'verbose_name_plural': 'Rappels de révision',
                'ordering': ['date_rappel'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('date_echange', models.DateTimeField(auto_now_add=True)),
                ('contexte_utilise', models.JSONField(blank=True, default=dict)),
                ('type_echange', models.CharField(choices=[('general', 'Général'), ('revision', 'Révision'), ('exercice', 'Exercice'), ('explication', 'Explication')], default='general', max_length=20)),
                ('session_ia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_chats', to='repetiteur_ia.sessionia')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_chats', to=settings.AUTH_USER_MODEL)),
                ('session_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_chats', to='repetiteur_ia.sessionrevisionprogrammee')),
            ],
            options={
                'verbose_name': 'Historique de chat',
                'verbose_name_plural': 'Historiques de chat',
                'ordering': ['-date_echange'],
            },
        ),
        migrations.CreateModel(
            name='SoumissionCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_soumission', models.CharField(choices=[('texte', 'Texte'), ('fichier', 'Fichier'), ('audio', 'Audio')], max_length=20)),
                ('contenu_texte', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='soumissions_eleves/%Y/%m/%d/')),
                ('transcription_audio', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('resume_automatique', models.TextField(blank=True)),
                ('matiere', models.CharField(blank=True, max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='repetiteur_ia.sessionrevisionprogrammee')),
            ],
            options={
                'verbose_name': 'Soumission de cours',
                'verbose_name_plural': 'Soumissions de cours',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='PlanificationAutomatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('frequence_revision', models.IntegerField(default=2)),
                ('duree_session', models.IntegerField(default=45)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planifications_auto', to='utilisateurs.eleve')),
            ],
            options={
                'verbose_name': 'Planification automatique',
                'verbose_name_plural': 'Planifications automatiques',
                'unique_together': {('eleve', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='ProgressionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('chapitre', models.CharField(max_length=200)),
                ('pourcentage_maitrise', models.IntegerField(default=0)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_revision', models.DateTimeField(blank=True, null=True)),
                ('notes_personnelles', models.TextField(blank=True)),
                ('difficultes_identifiees', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_revisions', to='utilisateurs.eleve')),
            ],
            options={
                'verbose_name': 'Progression de révision',
                'verbose_name_plural': 'Progressions de révision',
                'unique_together': {('eleve', 'matiere', 'chapitre')},
            },
        ),
    ]
