# Generated by Django 5.0.3 on 2025-10-27 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetiteur_ia', '0004_documentpedagogique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conversation', models.CharField(choices=[('session', 'Session de révision'), ('libre', 'Conversation libre'), ('soumission', 'Soumission de cours')], default='libre', max_length=20)),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('contexte_utilise', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='repetiteur_ia.sessionrevisionprogrammee')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de conversation',
                'verbose_name_plural': 'Historiques de conversations',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'date_creation'], name='repetiteur__utilisa_4edc5b_idx'), models.Index(fields=['session', 'date_creation'], name='repetiteur__session_503d67_idx')],
            },
        ),
    ]
