# Generated by Django 5.0.3 on 2025-10-30 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0009_alter_quiz_options_and_more'),
        ('repetiteur_ia', '0005_historiqueconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrevisionprogrammee',
            name='quiz_genere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_revision', to='cours.quiz'),
        ),
        migrations.AddField(
            model_name='soumissioncours',
            name='quiz_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumissions_associees', to='cours.quiz'),
        ),
    ]
