# Generated by Django 5.0.3 on 2025-10-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='push_notifications',
            field=models.BooleanField(default=False, verbose_name='Notifications push'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='sms_notifications',
            field=models.BooleanField(default=False, verbose_name='Notifications par SMS'),
        ),
    ]
