# Generated by Django 5.0.3 on 2025-10-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_emailconfirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
