# Generated by Django 5.0.3 on 2025-12-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_delete_emailconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='notifications_evaluations',
            field=models.BooleanField(default=True, verbose_name='Nouvelles évaluations'),
        ),
        migrations.AddField(
            model_name='parent',
            name='notifications_hebdomadaires',
            field=models.BooleanField(default=True, verbose_name='Rapports hebdomadaires'),
        ),
        migrations.AddField(
            model_name='parent',
            name='notifications_quiz',
            field=models.BooleanField(default=True, verbose_name='Nouveaux quiz réalisés'),
        ),
        migrations.AddField(
            model_name='parent',
            name='notifications_quotidiennes',
            field=models.BooleanField(default=True, verbose_name='Notifications quotidiennes'),
        ),
    ]
