# Generated by Django 5.0.3 on 2025-10-14 15:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_push_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_debut_abonnement', models.DateField(blank=True, null=True)),
                ('date_fin_abonnement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('complet', 'Complété'), ('en_attente', 'En attente'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('methode', models.CharField(default='', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.eleve')),
            ],
            options={
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
