# Generated by Django 5.0.3 on 2025-10-10 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_push_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('matiere', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='utilisateurs.professeur')),
            ],
            options={
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='CoursCoursEleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves_inscrits', to='cours.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_suivis_table', to='utilisateurs.eleve')),
            ],
            options={
                'verbose_name': 'Inscription à un cours',
                'verbose_name_plural': 'Inscriptions aux cours',
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='eleves',
            field=models.ManyToManyField(blank=True, related_name='cours_suivis', through='cours.CoursCoursEleves', to='utilisateurs.eleve'),
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('jour_semaine', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois', to='utilisateurs.eleve')),
            ],
            options={
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['jour_semaine', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('questions', models.JSONField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='cours.cours')),
            ],
            options={
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.eleve')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cours.quiz')),
            ],
            options={
                'unique_together': {('cours', 'eleve')},
            },
        ),
    ]
