# Generated by Django 5.0.3 on 2025-10-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['matiere', 'titre'], 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterField(
            model_name='cours',
            name='matiere',
            field=models.CharField(choices=[('mathématiques', 'Mathématiques'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('français', 'Français'), ('anglais', 'Anglais'), ('espagnol', 'Espagnol'), ('histoire', 'Histoire'), ('géographie', 'Géographie'), ('philosophie', 'Philosophie'), ('svt', 'SVT'), ('technologie', 'Technologie'), ('eps', 'EPS'), ('musique', 'Musique'), ('arts plastiques', 'Arts Plastiques')], max_length=100, verbose_name='Matière'),
        ),
    ]
