# Generated by Django 5.0.3 on 2025-10-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='emplois_du_temps/'),
        ),
    ]
