# Generated by Django 5.0.3 on 2025-10-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_alter_cours_options_alter_cours_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.CharField(blank=True, choices=[('collège', 'Collège'), ('lycée', 'Lycée')], max_length=20, null=True, verbose_name='Niveau scolaire'),
        ),
    ]
