# Generated by Django 5.0.3 on 2025-10-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_cours_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='fichier',
            field=models.FileField(blank=True, help_text='Téléchargez un document support (PDF, PowerPoint, Word, etc.)', null=True, upload_to='cours_fichiers/%Y/%m/%d/', verbose_name='Document du cours'),
        ),
    ]
