# Generated by Django 5.0.3 on 2025-10-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_emploidutemps_document'),
        ('cours', '0004_cours_fichier'),
    ]

    operations = [
    ]
