# Generated by Django 5.0.3 on 2025-10-27 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_alter_quiz_options_and_more'),
        ('utilisateurs', '0004_delete_emailconfirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['ordre'], 'verbose_name': 'Choix', 'verbose_name_plural': 'Choix'},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['matiere', 'niveau', 'titre'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='emploidutemps',
            options={'ordering': ['jour_semaine', 'heure_debut'], 'verbose_name': 'Emploi du temps', 'verbose_name_plural': 'Emplois du temps'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name': 'Évaluation', 'verbose_name_plural': 'Évaluations'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['ordre'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quiz'},
        ),
        migrations.RemoveField(
            model_name='emploidutemps',
            name='eleve',
        ),
        migrations.AddField(
            model_name='choice',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='cours',
            name='cycle',
            field=models.CharField(blank=True, choices=[('collège', 'Collège'), ('lycée', 'Lycée')], max_length=20, null=True, verbose_name='Cycle scolaire'),
        ),
        migrations.AddField(
            model_name='cours',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='duree_estimee',
            field=models.PositiveIntegerField(blank=True, help_text='Durée estimée pour compléter ce cours', null=True, verbose_name='Durée estimée (minutes)'),
        ),
        migrations.AddField(
            model_name='cours',
            name='est_public',
            field=models.BooleanField(default=True, help_text='Si cochée, le cours est visible par tous les élèves du niveau', verbose_name='Cours public'),
        ),
        migrations.AddField(
            model_name='cours',
            name='objectifs',
            field=models.TextField(blank=True, help_text="Objectifs d'apprentissage pour ce cours", verbose_name='Objectifs pédagogiques'),
        ),
        migrations.AddField(
            model_name='cours',
            name='tags',
            field=models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=255, verbose_name='Mots-clés'),
        ),
        migrations.AddField(
            model_name='courscourseleves',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Inscription active'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='cours.cours'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='salle',
            field=models.CharField(blank=True, max_length=50, verbose_name='Salle'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='question',
            name='explication',
            field=models.TextField(blank=True, verbose_name='Explication de la réponse'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='cours.cours', verbose_name='Cours associé'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duree',
            field=models.PositiveIntegerField(default=30, help_text='Durée estimée pour compléter le quiz', verbose_name='Durée (minutes)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Quiz actif'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='points_max',
            field=models.PositiveIntegerField(default=20, verbose_name='Points maximum'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='est_correcte',
            field=models.BooleanField(default=False, verbose_name='Est correcte'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='texte',
            field=models.CharField(max_length=512, verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='contenu',
            field=models.TextField(verbose_name='Contenu du cours'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='fichier',
            field=models.FileField(blank=True, help_text='Téléchargez un document support (PDF, PowerPoint, Word, etc.) - Max 10MB', null=True, upload_to='cours_fichiers/%Y/%m/%d/', verbose_name='Document du cours'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.CharField(blank=True, choices=[('6ème', 'Sixième'), ('5ème', 'Cinquième'), ('4ème', 'Quatrième'), ('3ème', 'Troisième'), ('2nde', 'Seconde'), ('1ère', 'Première'), ('Tle', 'Terminale')], max_length=20, null=True, verbose_name='Niveau scolaire'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre du cours'),
        ),
        migrations.AlterField(
            model_name='courscourseleves',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='emplois_du_temps/%Y/%m/', verbose_name='Document associé'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='heure_debut',
            field=models.TimeField(verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='heure_fin',
            field=models.TimeField(verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='jour_semaine',
            field=models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10, verbose_name='Jour'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='matiere',
            field=models.CharField(max_length=100, verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='cours.cours'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'évaluation"),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='utilisateurs.eleve'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='note',
            field=models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='cours.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='question',
            name='texte',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by_ai',
            field=models.BooleanField(default=False, verbose_name='Généré par IA'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre du quiz'),
        ),
        migrations.AlterUniqueTogether(
            name='courscourseleves',
            unique_together={('eleve', 'cours')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'ordre')},
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['matiere', 'niveau'], name='cours_cours_matiere_271c55_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['professeur'], name='cours_cours_profess_8dda44_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['date_creation'], name='cours_cours_date_cr_804b26_idx'),
        ),
        migrations.AddIndex(
            model_name='courscourseleves',
            index=models.Index(fields=['eleve', 'cours'], name='cours_cours_eleve_i_5bf7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='emploidutemps',
            index=models.Index(fields=['jour_semaine', 'heure_debut'], name='cours_emplo_jour_se_fd6d35_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['cours', 'eleve'], name='cours_evalu_cours_i_538aad_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['eleve'], name='cours_evalu_eleve_i_ea9de4_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['cours'], name='cours_quiz_cours_i_827763_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['created_by'], name='cours_quiz_created_058fab_idx'),
        ),
    ]
