# Generated by Django 5.0.3 on 2025-10-27 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_alter_choice_options_alter_cours_options_and_more'),
        ('utilisateurs', '0004_delete_emailconfirmation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emploidutemps',
            name='cours_emplo_jour_se_fd6d35_idx',
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='eleve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='utilisateurs.eleve', verbose_name='Élève'),
        ),
        migrations.AddIndex(
            model_name='emploidutemps',
            index=models.Index(fields=['eleve', 'jour_semaine', 'heure_debut'], name='cours_emplo_eleve_i_e7acfc_idx'),
        ),
    ]
