# Generated by Django 5.0.3 on 2025-10-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0008_remove_emploidutemps_cours_emplo_jour_se_fd6d35_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quiz'},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='created_at',
            new_name='date_creation',
        ),
    ]
