# Generated by Django 5.0.3 on 2025-10-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0009_alter_quiz_options_and_more'),
        ('utilisateurs', '0004_delete_emailconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('repondue', models.BooleanField(default=False)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.question')),
            ],
            options={
                'verbose_name': 'Question de session',
                'verbose_name_plural': 'Questions de session',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0, verbose_name='Score (%)')),
                ('points_obtenus', models.IntegerField(default=0, verbose_name='Points obtenus')),
                ('points_max', models.IntegerField(default=0, verbose_name='Points maximum')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné')], default='en_cours', max_length=20)),
                ('duree_secondes', models.IntegerField(default=0, verbose_name='Durée (secondes)')),
                ('temps_restant', models.IntegerField(blank=True, null=True, verbose_name='Temps restant (secondes)')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='utilisateurs.eleve')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cours.quiz')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reponse', models.DateTimeField(auto_now=True)),
                ('points_obtenus', models.IntegerField(default=0)),
                ('est_correcte', models.BooleanField(default=False)),
                ('temps_reponse', models.IntegerField(default=0, verbose_name='Temps de réponse (secondes)')),
                ('choix_selectionnes', models.ManyToManyField(blank=True, to='cours.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.question')),
                ('tentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='cours.quizattempt')),
            ],
            options={
                'verbose_name': 'Réponse à une question',
                'verbose_name_plural': 'Réponses aux questions',
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin_prevue', models.DateTimeField()),
                ('temps_restant', models.IntegerField(verbose_name='Temps restant (secondes)')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='utilisateurs.eleve')),
                ('question_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.question')),
                ('questions_repondues', models.ManyToManyField(related_name='sessions_quiz', through='cours.QuestionSession', to='cours.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cours.quiz')),
            ],
            options={
                'verbose_name': 'Session de quiz',
                'verbose_name_plural': 'Sessions de quiz',
            },
        ),
        migrations.AddField(
            model_name='questionsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.quizsession'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'eleve'], name='cours_quiza_quiz_id_1ce24a_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['date_debut'], name='cours_quiza_date_de_40392b_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['tentative', 'question'], name='cours_quest_tentati_7e4e8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together={('tentative', 'question')},
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['quiz', 'eleve'], name='cours_quizs_quiz_id_5fa73d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionsession',
            unique_together={('session', 'question')},
        ),
    ]
